[build]
  command = "npm run build"
  publish = "out"

# Redirect rules for SPA routing
[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/index.html"
  status = 200

# Catch-all redirect for any other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
